image:  registry.gitlab.com/src_prepare/gentoo-repoman-container:latest

variables:
  GIT_SUBMODULE_STRATEGY: recursive

pkgcheck_ci:
  script:
    - pkgcheck ci --color 1
  allow_failure: true

pkgcheck_commit:
  rules:
    - if: $CI_PIPELINE_SOURCE != 'merge_request_event'
  script:
    - pkgcheck scan --color 1 --commits $CI_COMMIT_SHA

pkgcheck_merge:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
  script:
    - pkgcheck scan --color 1 --commits $CI_MERGE_REQUEST_DIFF_BASE_SHA..$CI_COMMIT_SHA

