image:  ghcr.io/pkgcore/pkgcheck:latest


# Requirements:
# * A project access token with read_repository and write_repository scopes
# * GITLAB_TOKEN (the token itself)
# * GITLAB_TOKEN_NAME (the name of the user commiting, GitLab creates fake users with the name @project_<project_id>_bot_<random_hash>)

# Optional variables:
# * METADATA_BRANCH otherwise "metadata"

stages:
  - check
  - deploy

.pkgcheck: &pkgcheck
  stage: check
  cache:
    key: md5-cache
    paths:
      - metadata/md5-cache
  script:
    - pmaint sync gentoo
    - pmaint regen $PMAINT_ARGS .
    - git config --global --add safe.directory '*'
    - pkgcheck --color y ci --failures ~/failures.json --exit GentooCI $PKGCHECK_ARGS
    - pkgcheck replay --color y ~/failures.json

pkgcheck_ci:
  <<: *pkgcheck
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
      when: manual
      allow_failure: true
    - if: $CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH
      when: manual
  artifacts:
    name: metadata
    paths:
      - metadata/md5-cache
      - metadata/pkg_desc_index
      - profiles/use.local.desc
  variables:
    # For reuse in the metadata deploy job
    PMAINT_ARGS: "--use-local-desc --pkg-desc-index"

pkgcheck_merge:
  <<: *pkgcheck
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
  variables:
    PKGCHECK_ARGS: "--commits $CI_MERGE_REQUEST_DIFF_BASE_SHA..$CI_COMMIT_SHA"

metadata:
  stage: deploy
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH
      variables:
        METADATA_BRANCH: "metadata_test"
      when: manual
  dependencies:
    - pkgcheck_ci
  variables:
    GIT_STRATEGY: fetch
    GIT_CHECKOUT: "false"
  before_script:
    - |-
      if git ls-remote --exit-code origin "${METADATA_BRANCH:-metadata}"; then
        git fetch origin "${METADATA_BRANCH:-metadata}"
      fi
    - git config --global user.email "${GITLAB_TOKEN_NAME}@noreply.gitlab.com"
    - git config --global user.name "${GITLAB_TOKEN_NAME}"
  script:
    - |-
      if git ls-remote --exit-code origin "${METADATA_BRANCH:-metadata}"; then
        git checkout -B "${METADATA_BRANCH:-metadata}" origin/"${METADATA_BRANCH:-metadata}"
      else
        git checkout -b "${METADATA_BRANCH:-metadata}"
      fi
    - git merge "${CI_COMMIT_SHA}"
    - git add -f metadata/md5-cache metadata/pkg_desc_index profiles/use.local.desc
    - |-
      CHANGES=$(git status --porcelain | wc -l)
      if [[ ${CHANGES} -gt 0 ]]; then
        git status
        git commit -m "$(date "+%F %R %Z")"
      fi
    - git push "https://${GITLAB_TOKEN_NAME}:${GITLAB_TOKEN}@${CI_SERVER_HOST}/${CI_PROJECT_PATH}.git" "${METADATA_BRANCH:-metadata}" -o ci.skip
