image:  ghcr.io/pkgcore/pkgcheck:latest

.pkgcheck: &pkgcheck
  cache:
    key: pkgcheck
    paths:
      - .cache/pkgcheck
  script:
    - pmaint sync gentoo
    - pmaint regen --dir "$CI_PROJECT_DIR/.cache/pkgcheck/repos" .
    - git config --global --add safe.directory '*'
    - pkgcheck --color y ci --cache-dir .cache/pkgcheck --failures ~/failures.json --exit GentooCI $PKGCHECK_ARGS
    - pkgcheck replay --color y ~/failures.json

pkgcheck_ci:
  <<: *pkgcheck
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
      when: manual
      allow_failure: true
    - if: $CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH
      when: manual

pkgcheck_merge:
  <<: *pkgcheck
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
  variables:
    PKGCHECK_ARGS: "--commits $CI_MERGE_REQUEST_DIFF_BASE_SHA..$CI_COMMIT_SHA"
