#!/usr/bin/env bash
set -e

version="${1}"
srcdir="${HOME}/sources/coolercontrol"
projectid="32909921"

if [[ -z ${version} ]]; then
    echo "No version given"
    exit 1
fi

if ! git --version >/dev/null ; then
    echo "dev-vcs/git missing"
    exit 1
fi
if ! npm --version >/dev/null ; then
    echo "pnpm missing"
    echo "either net-libs/nodejs[npm]"
    exit 1
fi
if ! zstd --version >/dev/null ; then
    echo "app-arch/zstd missing"
    exit 1
fi
if ! tar --version >/dev/null ; then
    echo "app-arch/tar missing"
    exit 1
fi
if ! gitlab_upload_package -h >/dev/null ; then
    echo "app-misc/parona-scripts missing"
    exit 1
fi

if ! [[ -d ${srcdir} ]]; then
    echo "${srcdir} missing"
    exit 1
fi
pushd "${srcdir}" >/dev/null
if ! git status >/dev/null ; then
    echo "${srcdir} is not a git directory"
    exit 1
fi
popd >/dev/null

gitlab_upload_package -v

outdir="$(mktemp -d)"
echo "Output directory: ${outdir}"

pushd "${srcdir}"
git fetch
git checkout "${version}"
pushd coolercontrol-ui
make dist
XZ_OPT='-T0 -9' tar -acf "${outdir}/coolercontrol-${version}-dist.tar.xz" dist
popd

gitlab_upload_package "${projectid}" coolercontrol "${version}" "${outdir}/coolercontrol-${version}-dist.tar.xz"

rm -rf "${outdir}"
git clean -fdx
git checkout "$(git symbolic-ref refs/remotes/origin/HEAD | sed 's@^refs/remotes/origin/@@')"
